### ISSUE TITLE
Support DRF > 3.0

### ISSUE THREAD

**Issue by RayeN** [yola/drf-madprops#9]
Implementation of serializers was significantly changed from 2.x.x to 3.x.x.  We need to add separate `PropertySerializers` for 3.x.x

**Comment by snitch** [comment]
@ekoval: This issue is now a priority.

**Comment by ekoval** [comment]
##### Status
Working. Unfortunately, DRF 3.x has lots of changes in serializers, so it's not easy.

**Comment by ekoval** [comment]
I have not very good news about madprops-drf3.x - DRF 3.0 introduced a limitation and don't support nested writable serializers anymore. Thus, if we have a serializers like these:
```
UserSerializer(ModelSerializer):
      preferences = MadPropsSerializer(...)
```
, we can't make preferences writable (which we really need). The only way to achieve this is to override `.create()` and `.update()` methods in the parent serializer (User). Which is bad for us, because `madprops` will have to depend on parent serializer implementation.
If the upgrade to DRF 3.x is still critical, the only solution is to override those two methods in a parent serializers.
Ping @RayeN @thomasw

**Comment by zoidbergwill** [comment]
Updating the `.create` and `.update` methods is the recommended way to do this, and if they try save without updating their methods, apparently they'll get an error anyway:

```
AssertionError: The `.create()` method does not support nested writable fields by default. Write an explicit `.create()` method for serializer `UserSerializer`, or set `read_only=True` on nested serializer fields.
```

**Comment by ekoval** [comment]
Yes. I'm saying that madprops usage will never be as convenient as it was before :(

**Comment by zoidbergwill** [comment]
It's supposed to be better now, but it does mean more lines of code. :P

**Comment by ekoval** [comment]
Why better? It requires more work from user of MadProps.

**Comment by zoidbergwill** [comment]
The [release notes](http://www.django-rest-framework.org/topics/3.0-announcement/#django-rest-framework-30) main reason is "REST framework 2.x attempted to automatically support writable nested serialization, but the behaviour was complex and non-obvious".

**Comment by ekoval** [comment]
Yes, I saw it. But it used to work fine for us :(

**Comment by stefanor** [comment]
Could we include a class to use as the parent serializer, that provides the right create and update behaviour?

**Comment by RayeN** [comment]
Yeah, I think that would be a right solution (proposed it as well, but offline)

**Comment by ekoval** [comment]
2 @stefanor  :
Yes, but this makes MadProps worse.

**Comment by stefanor** [comment]
No arguing that...

**Comment by ekoval** [comment]
##### Status
Waiting for code review.
